name: Publish on npm
on: push

jobs:
  #TODO: should be moved in test.yaml
  test:
    if: contains(join(github.event.commits.*.message, ' | '), '📦 Publicodes v1.0.0-beta.')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
    - run: yarn install --frozen-lockfile
    - working-directory: ./example/publicodes-react
      run: |
        yarn install
        yarn test

  publish:
    needs: test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
    - run: yarn install --frozen-lockfile
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_PUBLISH_SECRET }}
        dry-run: ${{ github.ref != 'refs/heads/master' }}
        package: ./core/package.json
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_PUBLISH_SECRET }}
        dry-run: ${{ github.ref != 'refs/heads/master' }}
        package: ./ui-react/package.json
